services:
  postgres:
    image: postgres:17
    container_name: naija-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: naija
      POSTGRES_USER: naija
      POSTGRES_PASSWORD: naija_dev_password

    ports:
      - "5432:5432"

    volumes:
      - naija_postgres_data:/var/lib/postgresql/data

volumes:
  naija_postgres_data: